#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Mizuki Kume
# SPDX-License-Identifier: BSD-3-Clause
import sys

Ans = 0 
Bin = 0 
Hex = 0 

for line in sys.stdin:
    try:
        Ans += int(line)
    except:
        Ans += float(line)

Bin = bin(Ans)
Hex = hex(Ans)

print(Ans,Bin,Hex) #出力
